### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by MarkTiedemann** [sindresorhus/lock-cli#1]
Are you interested in Windows support for this CLI?

I currently just execute [`tsdiscon`](https://technet.microsoft.com/en-us/library/bb490805.aspx) to lock my laptop (but not sure it's the best solution).

**Comment by sindresorhus** [comment]
If someone does a good PR, sure.

**Comment by MarkTiedemann** [comment]
Would something like this work for you?

`bin.js`
```js
#!/usr/bin/env node

const { execFileSync } = require('child_process')
const os = process.platform

switch (os) {
  case 'darwin': return execFileSync('lock')
  case 'win32': return execFileSync('tsdiscon')
  default: throw new Error(`unsupported os: ${os}`)
}
```

If so, I'd gladly do a PR later.

**Comment by sindresorhus** [comment]
Yes, but I think it should be implemented in https://github.com/sindresorhus/lock-system and just depend on that module here.

**Comment by MarkTiedemann** [comment]
All right, cool! Didn't know about that repo.
